spring.application.name=uniops-ticketing-service

# MongoDB Connection
spring.data.mongodb.uri=mongodb+srv://uniops_db_user:uniops@cluster0.znyobu6.mongodb.net/uniops_db?retryWrites=true&w=majority&appName=Cluster0&connectTimeoutMS=5000&serverSelectionTimeoutMS=5000
spring.data.mongodb.auto-index-creation=true

server.port=8089

# File Upload Configuration
file.upload-dir=uploads/tickets
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB

# Email Configuration (Mailtrap for testing)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=votifysliit@gmail.com
spring.mail.password=dqxwrxppjtfzvsiw
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.ssl.trust=smtp.gmail.com

spring.security.oauth2.client.registration.google.client-id=YOUR_GOOGLE_CLIENT_ID
spring.security.oauth2.client.registration.google.client-secret=YOUR_GOOGLE_CLIENT_SECRET
spring.security.oauth2.client.registration.google.scope=email,profile

spring.security.oauth2.client.provider.google.authorization-uri=https://accounts.google.com/o/oauth2/v2/auth
spring.security.oauth2.client.provider.google.token-uri=https://oauth2.googleapis.com/token
spring.security.oauth2.client.provider.google.user-info-uri=https://www.googleapis.com/oauth2/v3/userinfo
spring.security.oauth2.client.provider.google.user-name-attribute=sub

SENDER_EMAIL=rkamadhushadeshan751@gmail.com

SENDER_PASSWORD=fgpgcgfhwncdrkdb
