spring.application.name=uniops-ticketing-service

# MongoDB Connection
spring.data.mongodb.uri=mongodb+srv://uniops_db_user:uniops@cluster0.znyobu6.mongodb.net/uniops_db?retryWrites=true&w=majority&appName=Cluster0&connectTimeoutMS=5000&serverSelectionTimeoutMS=5000
spring.data.mongodb.auto-index-creation=true

server.port=8089

# File Upload Configuration
file.upload-dir=uploads/tickets
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB
