# ============================================================
# Smart Campus Operations Hub - Application Configuration
# Member 1: Facilities & Assets Catalogue
# ============================================================

# Server
server.port=8081
server.servlet.context-path=/api
spring.security.user.name=admin
spring.security.user.password=1234


# ── Database ────────────────────────────────────────────────
spring.datasource.url=jdbc:mysql://localhost:3307/smart_campus_db?allowPublicKeyRetrieval=true&useSSL=false
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ── JPA / Hibernate ─────────────────────────────────────────
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

# ── Jackson ─────────────────────────────────────────────────
spring.jackson.serialization.WRITE_DATES_AS_TIMESTAMPS=false
spring.jackson.time-zone=Asia/Colombo

# ── Logging ─────────────────────────────────────────────────
logging.level.com.smartcampus=DEBUG
logging.level.org.springframework.security=INFO

